### ISSUE TITLE
Failed to perform the action tdarr.refresh_library. Library Name not found

### ISSUE THREAD

**Issue by CZonin** [itchannel/tdarr_ha#32]
I'm trying to run the action `tdarr.refresh_library` but keep running into the error `Failed to perform the action tdarr.refresh_library. Library Name not found`. I'm formatting the name the same as it shows in tdarr (ie. Movies). Is there specific formatting I should be using?

```
action: tdarr.refresh_library
data:
  folderpath: /media/movies
  mode: scanFindNew
  library: Movies
```
