### ISSUE TITLE
[Feature Request] Cancel all transcodes and pause node

### ISSUE THREAD

**Issue by vodkapmp** [itchannel/tdarr_ha#34]
I'd love to be able to setup automations that in addition to pausing a node, would cancel all ongoing transcodes.

The idea is that if my UPS changes state to on-battery, I would get HA to kill any ongoing transcodes and pause the node(s) to extend the battery runtime.

**Comment by dennis-vanstrien** [comment]
I would also like the option to cancel transcodes, but for different purposes. My use case is to set up an automation where, when Plex starts transcoding, all ongoing transcode jobs in Tdarr are automatically stopped.

**Comment by itchannel** [comment]
This is added in the latest Beta (1.19 Beta 3). It can be used by calling the service below with the given node name:

```
action: tdarr.cancel_workers_by_node_name
data:
  node_name: Media Server
  cause: system maintenance
  ```
